files:
  - source: /TMessagesProj/src/main/res/values/strings_na.xml
    translation: /TMessagesProj/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      two_letters_code:
        he: iw
        es-VE: es-rVE
        pt-BR: pt-rBR
        zh-CN: zh-rCN
        id: in
bundles:
  - 2
